server:
  port: 8081

management:
  web:
    exposure:
      include: mappings

spring:
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: <username>
    password: <password>
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true
  profiles:
    active: loadInitialData
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true